### ISSUE TITLE
Crash with multirail providers.

### ISSUE THREAD

**Issue by dmaryin** [aws/aws-ofi-nccl#102]
Hello aws-ofi-nccl maintainers,

In case if underlying provider (PSM3 in our case) is able to provide support for multi-rail, it typically exposes virtual device with NULL name. Plugin blindly strdups this name and in case of NULL there segfault happens.
#101 fixes this. 
Could you please consider merging it?

BRs,
Denis.

**Comment by nzmsv** [comment]
Fixed by #101, #105
