### ISSUE TITLE
[Question] Is RDMA available on p3dn instances?

### ISSUE THREAD

**Issue by kiukchung** [aws/aws-ofi-nccl#104]
Looking at the [docs](https://aws.amazon.com/about-aws/whats-new/2020/11/efa-supports-nvidia-gpudirect-rdma/) and having run some test jobs on p3dn instances, it looks like GPU RDMA over EFA is not available on p3dn instances and only on p4d? Is this correct?

Some observations on p3dn (running a fairseq - pytorch - training job using the nccl backend):

1. `NCCL_ALGO = tree` is faster than `NCCL_ALGO=ring` (assuming no RDMA on p3dn, I'm thinking this is due to two copies: DtoH -> HtoH (inter node, over EFA) -> HtoD)
2. With `NCCL_DEBUG=INFO` we're observing debug logs like:
     ```
      [0]:ip-10-0-0-157:24:146 [0] NCCL INFO Channel 00 : 12[1a0] -> 0[160] [receive] via NET/AWS Libfabric/0

      # -- NOT --
      [0]:ip-10-0-0-157:24:146 [0] NCCL INFO Channel 00 : 12[1a0] -> 0[160] [receive] via NET/AWS Libfabric/0/GDRDMA
     ```
3. `nv_peer_mem` is not loaded:
     ```
      $ lsmod | grep nv
      root@ip-10-0-0-159:/# lsmod | grep nv
      nvidia_drm             61440  0
      nvidia_modeset       1196032  1 nvidia_drm
      nvidia_uvm           1138688  16
      nvidia              35262464  2858 nvidia_uvm,nvidia_modeset
      drm_kms_helper        184320  1 nvidia_drm
      drm                   425984  4 drm_kms_helper,nvidia,nvidia_drm
      i2c_core               77824  3 drm_kms_helper,nvidia,drm
    ```

**Comment by nzmsv** [comment]
This is correct.  GPUDirect RDMA is not enabled on p3dn due to its PCI topology (the GPU and NIC are not on the same switch).  In our testing using GDRDMA on p3dn was worse than not enabling it.  If you'd like to try it in your environment you can increase the value of the `NCCL_NET_GDR_LEVEL` environment variable (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-net-gdr-level-formerly-nccl-ib-gdr-level).

**Comment by kiukchung** [comment]
thank you for confirming! Curious, do you have any prior benchmarks in running nccl tests on p3dn on baremetal versus inside a docker container? Same test binary, just one directly on the host (ssh into the instance and execute the test) versus running it as `docker run --device /dev/infiniband/uverbs0 test_image`) we're observing nearly a 2x perf drop for fairseq training when running inside docker versus on baremetal on p3dn. Wondering if we need to set some special options (e.g. `--net=host`) when running in docker to match the performance. (see: https://github.com/pytorch/torchx/issues/444)

**Comment by kiukchung** [comment]
I see you commented on the torchx-issue-444, we can follow up there, thanks!

**Comment by rashikakheria** [comment]
We have conducted benchmarks on p3dn instances and on docker. There shouldn't be any difference in performance if you provide all GPUs and Net device access to the the docker container. I would confirm if you are using EFA in your benchmarks inside docker.

**Comment by kiukchung** [comment]
Seems like the base docker image pytorch-training:1.10.2-gpu-py38-cu113-ubuntu20.04-e3 doesn't come ready with aws-ofi-nccl preinstalled/configured. We're seeing that manually reinstalling nccl and aws-ofi-nccl (from source) brings back the perf parity with baremetal. Is this a known issue?

**Comment by rashikakheria** [comment]
@kiukchung No, our team doesn't prepare docker images for ML training. Could you tell us which NCCL+aws-ofi-nccl version was used as part of docker compared to the one in baremetal?
