### ISSUE TITLE
[Feature Request]Allow custom NCCL_TOPO_FILE location

### ISSUE THREAD

**Issue by roywei** [aws/aws-ofi-nccl#150]
Currently on the aws branch, ofi will use the `--prefix` location during configure to store the xml topology files. It will set XML_DIR to prefix value during compile time. https://github.com/aws/aws-ofi-nccl/blob/aws/src/Makefile.am#L8

During runtime it will set `NCCL_TOPO_FILE` according to the `XML_DIR` value: https://github.com/aws/aws-ofi-nccl/blob/aws/src/nccl_ofi_net.c#L1178

This will create a problem when I build OFI plugin library at one place (a CI system), and package it and try to run it on another machine (e.g. via conda install to a $CONDA_PREFIX).

If build path (--prefx) and $CONDA_PREFIX does not match, OFI will fail to find topology file and result in a regression.

Could you update the logic to use NCCL_TOPO_FILE value if there is a preset environment variable? This will allow me to configure OFI to read XML files at any location. Also add logging on which topology file is used.

I'm  able to workaround this issue by using Conda's binary relocation patch, which will change the $PREFIX value during installation. But this is still a good feature to have.

Thanks!

**Comment by rashikakheria** [comment]
The reason plugin code sets the topo file explicitly is to ensure that right topology files are used when running on AWS systems. Now there is a chance that if you build it separately and copy the library to other location, we might miss porting the topology file leading to performance regression. Similarly overriding the `NCCL_TOPO_FILE` variable from customer configuration scripts, might also lead to performance regression in case the file doesn't exist. These customer configuration issues are hard to chase when debugging performance. Is it possible to build plugin in the conda environment?

**Comment by rashikakheria** [comment]
https://github.com/aws/aws-ofi-nccl/pull/173 should fix the issue.
