### ISSUE TITLE
Error running NCCL Tests via MPiJob: "prov_err Not a Directory"

### ISSUE THREAD

**Issue by Csinclair0** [aws/aws-ofi-nccl#156]
Running nccl tests on image public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3 results in results in the following errors. 

`[1,13]<stdout>:nccl-tests-worker-1:35:89 [5] ofi_process_cq:1039 NCCL WARN NET/OFI Request 0x7fbb944701b8 completed with error. RC: 20. Error: unknown error. Completed length: 0, Request: { buffer_index: 255, dev: 1, size: 0, state: CREATED, direction: SEND }
[1,13]<stderr>:libfabric:35:1668017255::efa:cq:rxr_cq_write_tx_error():243<warn> rxr_cq_write_tx_error: err: 20, prov_err: Not a directory (20)`

Full error log: https://gist.github.com/Csinclair0/48ee4f1388d4901e6958069ee272a305
MPIJob spec : https://gist.github.com/Csinclair0/18dcc46fb3ae98c189b9c5dcd56ead2f

**Comment by wzamazon** [comment]
Can you check the security group setting between ec2 instances? For EFA to work the instance must accept all inbound and outbound traffic to the same security group.

**Comment by Csinclair0** [comment]
That as indeed the issue, thanks for the help!
