### ISSUE TITLE
Support Ubuntu 22.04

### ISSUE THREAD

**Issue by tson1111** [aws/aws-ofi-nccl#203]
Do we have any plans on supporting Ubuntu 22.04?

**Comment by YoonGi-AWS** [comment]
We are working on the Ubuntu 22.04 support and there is a minor issue detected(GDRcopy install issue with latest kernel).
We will update again when the Ubuntu 22.04 verified.

**Comment by lanbochen-anyscale** [comment]
Hi @YoonGi-AWS, do you have an ETA when it will be ready?

**Comment by bwbarrett** [comment]
The 1.6 or later versions of the plugin should work on Ubuntu 22.04, based on spot testing.  As YoonGi mentioned, there were some issues with GDRCopy, but GDRCopy isn't strictly required for any of the AWS platforms (it helps with performance, but is not required).  We likely will not call Ubuntu 22.04 "supported" until the 1.8 series, just based on timelines of adding Ubuntu 22.04 to our test suite.  But we don't know of any problems today with 22.04.

**Comment by rauteric** [comment]
Ubuntu 22.04 is officially supported, with regular testing, as of v1.8.0-aws.
