### ISSUE TITLE
Running nccl-perf tests documentation is missing MPI instructions

### ISSUE THREAD

**Issue by tmh97** [aws/aws-ofi-nccl#255]
I ran into a bit of a headache because I wasn't referring to the [nccl-tests ](https://github.com/NVIDIA/nccl-tests) documentation when attempting to build the performance tests.

All I needed was to add `MPI=1 MPI_HOME=/path/to/mpi` and things worked well :)

Do you folks think it's reasonable to add this to the README.md? If so, I'll open a PR to close this out.

Something like:

```
2. Build the tests

cd nccl-tests/
make NCCL_HOME=~/nccl/build MPI=1 MPI_HOME=$MPI_HOME
```

**Comment by rauteric** [comment]
Thanks Thomas, yes we definitely should update this since building nccl-tests without MPI is not a valid use case for the plugin (NCCL won't use the plugin at all within-node).

I think we should also update the run command to use MPI.

**Comment by tmh97** [comment]
@rauteric Thanks for the quick response! I'll open a PR tomorrow to address this.

One question I have is, what would needed to be added to the run command to use MPI? I imagine maybe `LD_LIBRARY-PATH=/path/to/your/mpi/lib `

Let me know whatcha think.

**Comment by rauteric** [comment]
Well I really meant just using mpirun. 😄 We usually use one MPI rank per GPU, see the public AWS doc [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start-nccl-base.html#nccl-start-base-test).

Though yes, you would also need to update `LD_LIBRARY_PATH` if the MPI libraries aren't in your default path.
