### ISSUE TITLE
Add more examples with more recent cuda versions

### ISSUE THREAD

**Issue by tchaton** [aws/aws-ofi-nccl#296]
Hey there,

It would be great to have more examples for more recent versions of CUDA + compatibility table to make it easier to switch versions.

Best,
T.C

**Comment by rauteric** [comment]
Hello Thomas,

Could you clarify what examples you are referring to? Did you encounter any problems using this plugin with different versions of CUDA?

I'm not aware of any significant compatibility issues with different CUDA versions in the plugin.

**Comment by tchaton** [comment]
Hey @rauteric,

I have tried to bump it to `1.2.1` but I am getting some errors. 

```python
Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
[W CUDAFunctions.cpp:108] Warning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized (function operator())
>>> torch
<module 'torch' from '.../python3.10/site-packages/torch/__init__.py'>
>>> torch.cuda.is_available()
False
```

It would be great if you could add more examples for later versions. I might have something wrong somewhere.
