### ISSUE TITLE
RDMA protocol

### ISSUE THREAD

**Issue by eliekozah** [aws/aws-ofi-nccl#364]
I'm fixing a bug with our provider's use of RDMA. Does RDMA universally lack FI_CONTEXT support, or is this absence specific to AWS OFI NCCL's implementation?

**Comment by rauteric** [comment]
This absence is specific to Aws-ofi-nccl's RDMA protocol implementation. Context was omitted only for convenience in our first implementation, and can be added in the future.

**Comment by eliekozah-cornelisnetworks** [comment]
Hi @rauteric,

Thank you for the clarification. Our team is considering contributing a fix to introduce `FI_CONTEXT` support with RDMA and would love to get your thoughts on any implementation preferences or directions your team might have. This would help us tailor our contribution to fit into the project.

**Comment by rauteric** [comment]
Hi @eliekozah-cornelisnetworks,

Thank you for considering a contribution. In general, I think `FI_CONTEXT` support can be implemented similarly to how we implement it for the SENDRECV protocol (https://github.com/aws/aws-ofi-nccl/blob/master/src/nccl_ofi_sendrecv.c), by having a `fi_context` member of the request data structure.

The main obstacle we have currently to supporting `FI_CONTEXT` is that right now the context we use can be shared between multiple simultaneous Libfabric operations. The particular example I can find is RDMA write operations for individual rails: https://github.com/aws/aws-ofi-nccl/blob/2adb8f56553fe0946141180c4a119c96eca766d8/src/nccl_ofi_rdma.c#L4226-L4230 will all use the same context (`req`). To support `FI_CONTEXT` these would need to be split either into separate `fi_context` objects inside the request structure, or preferably, subrequests of the parent request structure.

There may be other examples of this in the current code, but that's the only one I can find at the moment.

**Comment by eliekozah-cornelisnetworks** [comment]
Hi @rauteric,

I see you remove the check of provider requiring FI_CONTEXT and provider support of RMA here:
https://github.com/aws/aws-ofi-nccl/blob/1006b3f0ec771781fd58790d6e200c86edf11f85/src/nccl_ofi_rdma.c#L5931

Any specific reason behind this change?

**Comment by rauteric** [comment]
Hi, this was mostly just a refactoring.

The previous code set `hints->mode = FI_CONTEXT` for both RDMA and SENDRECV protocols (since SENDRECV protocol supports it), so we needed some logic to check that the provider didn't enable it when using RDMA protocol.

Since a recent refactoring, the `hints->mode` parameter is set separately for the two protocols. The RDMA protocol does not include `FI_CONTEXT` in `hints->mode` (which means it does not support it), so it no longer needs the extra check.

Similarly, the check for `FI_RMA` support from provider is not needed since it is requested as a capability bit in the hints: https://github.com/aws/aws-ofi-nccl/blob/1006b3f0ec771781fd58790d6e200c86edf11f85/src/nccl_ofi_rdma.c#L5763-L5764

**Comment by eliekozah-cornelisnetworks** [comment]
> Hi @eliekozah-cornelisnetworks,
> 
> Thank you for considering a contribution. In general, I think `FI_CONTEXT` support can be implemented similarly to how we implement it for the SENDRECV protocol (https://github.com/aws/aws-ofi-nccl/blob/master/src/nccl_ofi_sendrecv.c), by having a `fi_context` member of the request data structure.
> 
> The main obstacle we have currently to supporting `FI_CONTEXT` is that right now the context we use can be shared between multiple simultaneous Libfabric operations. The particular example I can find is RDMA write operations for individual rails:
> 
> https://github.com/aws/aws-ofi-nccl/blob/2adb8f56553fe0946141180c4a119c96eca766d8/src/nccl_ofi_rdma.c#L4226-L4230
> 
> will all use the same context (`req`). To support `FI_CONTEXT` these would need to be split either into separate `fi_context` objects inside the request structure, or preferably, subrequests of the parent request structure.
> There may be other examples of this in the current code, but that's the only one I can find at the moment.

Hi @rauteric, 

just to confirm, by "rail" do you mean NIC? and does you implementation of RDMA always assume that there are multiple NICs in the network?

**Comment by rauteric** [comment]
> just to confirm, by "rail" do you mean NIC?

Yes. The RDMA protocol will group multiple NICs together and expose them to NCCL as a single NIC per GPU. The individual NICs are referred to as "rails" in the code.

> and does you implementation of RDMA always assume that there are multiple NICs in the network?

The protocol has some code to detect the number of NICs on the node and their proximity to the GPUs using hwloc. It should work even if there is only one NIC per node, or only one NIC per GPU. However, we don’t regularly test these configurations.

**Comment by eliekozah-cornelisnetworks** [comment]
Thanks, @rauteric for clarifying. One more question about the `req_lock` mutex lock field in the request structure. So you are trying to protect updating critical fields from access of other threads. Are these other threads created by the NCCL library or you assume they should be created by the libfabric provider?

**Comment by rauteric** [comment]
`req_lock` protects access from threads created by NCCL. We don't need to protect access to plugin data by threads created by the Libfabric provider, since the Libfabric provider shouldn't have access to any plugin data.
