### ISSUE TITLE
Building with release tarball throws `tuner_v1.h` not found error

### ISSUE THREAD

**Issue by sirutBuasai** [aws/aws-ofi-nccl#382]
I noticed that there's some discrepancy between the release tarball (https://github.com/aws/aws-ofi-nccl/releases/download/v1.9.0-aws/aws-ofi-nccl-1.9.0-aws.tar.gz) and the source code tarball (https://github.com/aws/aws-ofi-nccl/archive/refs/tags/v1.9.0-aws.tar.gz). The release tarball doesn't contain `tuner_v*.h` files while the source code do. 

As such, building with release tarball throws the following error: 
```
In file included from tuner/nccl_ofi_model.c:6:
../include/nccl-headers/nvidia/tuner.h:32:10: fatal error: tuner_v1.h: No such file or directory
   32 | #include "tuner_v1.h"
      |          ^~~~~~~~~~~~
compilation terminated.
```

However, building using the source code tarball is successful when running the following:
```
./autogen.sh
./configure \
  --prefix=$PREFIX \
  --with-mpi=/opt/amazon/openmpi \
  --with-libfabric=/opt/amazon/efa \
  --with-cuda=/usr/local/cuda-12.1 \
  --disable-tests
make
make install
```

**Comment by rajachan** [comment]
Thanks for reporting the issue, @sirutBuasai. The release artifact was indeed missing the headers. We are working on a bugfix release that should address this issue.
