### ISSUE TITLE
could not find header file nccl_net.h when installing from downloaded release

### ISSUE THREAD

**Issue by jackalcooper** [aws/aws-ofi-nccl#4]
```
[ec2-user@ip-172-31-23-78 aws-ofi-nccl-0.9]$ make
mpicc -I/opt/nccl/include -I/usr/local/cuda/include -I/opt/libfabric/include -I./include/ -o /home/ec2-user/oss/aws-ofi-nccl-0.9/tests/ring -L/home/ec2-user/oss/aws-ofi-nccl-0.9 -lnccl-net 		\
-L/opt/libfabric/lib -lfabric -L/usr/local/cuda/lib64 -lcudart 	\
/home/ec2-user/oss/aws-ofi-nccl-0.9/tests/ring.c -ldl
In file included from /home/ec2-user/oss/aws-ofi-nccl-0.9/tests/ring.c:5:0:
/home/ec2-user/oss/aws-ofi-nccl-0.9/tests/test-common.h:11:10: fatal error: nccl_net.h: No such file or directory
 #include <nccl_net.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [/home/ec2-user/oss/aws-ofi-nccl-0.9/tests/ring] Error 1
```

**Comment by jackalcooper** [comment]
```
checking for unistd.h... (cached) yes
checking rdma/fabric.h usability... no
checking rdma/fabric.h presence... no
checking for rdma/fabric.h... no
configure: error: unable to find required headers
```
MAKE with git clone. It checks header files of rdma.

**Comment by jackalcooper** [comment]
Thank you @rashikakheria ! Later I will get it another try. Besides getting it running, I am curious about the performance this plug-in brings to the table. We are trying to get rid of the bottleneck of 100Gbps AWS ENA due to CPU single core limitation. It would be wonderful if you could post some info on benchmarks and performance boost from naive NCCL incorporation.

**Comment by bwbarrett** [comment]
@jackalcooper, the primary driver for NCCL over libfabric is to support [EFA](https://aws.amazon.com/about-aws/whats-new/2018/11/introducing-elastic-fabric-adapter/) when it is officially released.  EFA will still be 100 Gbps, but should have lower CPU utilization than using ENA and will avoid the 10 Gbps flow limiters that require the use of a high number of rings in NCCL to drive the full 100 Gbps.

**Comment by rashikakheria** [comment]
Are there any other open questions @jackalcooper? If not, could we close this issue?

**Comment by jackalcooper** [comment]
@rashikakheria Thanks for asking. There is no other issue for now. I have built it and applied for EFA preview. Will test it again and report more on this if it is approved.
