### ISSUE TITLE
Seg Fault during RDMA NCCL Connection with OPX Provider

### ISSUE THREAD

**Issue by lsavers** [aws/aws-ofi-nccl#599]
I'm working at getting the NCCL plugin to work with the OPX Libfabric provider using the RDMA protocol and I am hitting a seg fault during nccl RDMA connection establishment.  The exception is happening in nccl_ofi_msgbuff_insert processing the connect message packet received.  r_comm->msg_buff is NULL, so it fails the assert (at https://github.com/aws/aws-ofi-nccl/blob/7a0fa83daad9d01c14b2895439e1dd5615cb6ebd/src/nccl_ofi_msgbuff.c#L138).  I see where this buffer is set when accept calls prepare_recv_comm; however, at the time OPX is in the connect processing, accept has not yet been invoked.

The RDMA connect() is in COMM_CONN_RESP_REQ_PENDING stage and processing completion entries from the CQ.  It seems like handle_bounce_recv() expects the connection messages to not have the eager boolean set on handle_bounce_recv; however, OPX sets FI_REMOTE_CQ_DATA.  Have you seen anything like this with the providers you have run with?  The SENDRECV protocol appears to be working properly, so I need to spend a little more time following that flow, but wanted to ask in case someone has run into this issue with another provider.

From nccl_ofi_rdma.c connect:
https://github.com/aws/aws-ofi-nccl/blob/7a0fa83daad9d01c14b2895439e1dd5615cb6ebd/src/nccl_ofi_rdma.c#L5824
  https://github.com/aws/aws-ofi-nccl/blob/7a0fa83daad9d01c14b2895439e1dd5615cb6ebd/src/nccl_ofi_rdma.c#L1720
    https://github.com/aws/aws-ofi-nccl/blob/7a0fa83daad9d01c14b2895439e1dd5615cb6ebd/src/nccl_ofi_rdma.c#L1675
      https://github.com/aws/aws-ofi-nccl/blob/7a0fa83daad9d01c14b2895439e1dd5615cb6ebd/src/nccl_ofi_rdma.c#L1430 ( comp_flags has FI_REMOTE_CQ_DATA set )
        https://github.com/aws/aws-ofi-nccl/blob/7a0fa83daad9d01c14b2895439e1dd5615cb6ebd/src/nccl_ofi_rdma.c#L1212
          https://github.com/aws/aws-ofi-nccl/blob/7a0fa83daad9d01c14b2895439e1dd5615cb6ebd/src/nccl_ofi_rdma.c#L1003
            https://github.com/aws/aws-ofi-nccl/blob/7a0fa83daad9d01c14b2895439e1dd5615cb6ebd/src/nccl_ofi_msgbuff.c#L138

**Comment by lsavers** [comment]
Thanks for the prompt response.  I see what you are saying and I am looking into why OPX sets it in this scenario.  I will follow up with additional questions if it seems valid, or close the issue if determined to be an issue to be resolved in OPX.

Side question:  I hit another issue (relating to the removal of fi_cq_tagged_entry in the nccl RDMA path) that I've worked around for now, but is it preferred to open up a unique issue for this, or update the title of this issue for discussion around any further issues hit trying to test RDMA NCCL with the OPX provider?

**Comment by AmedeoSapio** [comment]
I think having separate issues is better to keep the conversation more focused. Thanks for asking!

**Comment by lsavers** [comment]
Closing this issue as I believe an update is needed in OPX.  Thanks for your help.
