### ISSUE TITLE
"Request completed with error" log leads to p5e cluster collapse

### ISSUE THREAD

**Issue by vmarkovtsev** [aws/aws-ofi-nccl#611]
We had the following incident. 
We write our logs on local disk. For some reason, we had some EFA errors and this line in the plugin's source code executed with enormous frequency: https://github.com/aws/aws-ofi-nccl/blob/master/src/nccl_ofi_rdma.c#L2419

https://github.com/user-attachments/assets/b9c03137-699c-4d5f-a75c-7e6d7a135469

The frequency was so high that we wrote ~1GB of logs per second. By the time we noticed something was wrong, we managed to overwhelm the attached EBS and completely break the p5e machines (CASE 172662214700066). We had to restart them.

I suggest decreasing the log level to INFO, or adding log throttling, or fixing the possible infinite cycle.

**Comment by sanjams2** [comment]
@vmarkovtsev were you able to get to the root cause of the loop?
