### ISSUE TITLE
[Feature request] Topo file for g6e.48xlarge

### ISSUE THREAD

**Issue by sean-smith** [aws/aws-ofi-nccl#689]
Title says it all

**Comment by bwbarrett** [comment]
Why?  This is really not the right solution to whatever problem you're trying to solve.

**Comment by sean-smith** [comment]
nvm, for others wondering the topo files are automatically generated as of release [v1.11.0-aws](https://github.com/aws/aws-ofi-nccl/releases/tag/v1.11.0-aws)
