### ISSUE TITLE
1.13.0-aws release tarball does not contain -aws

### ISSUE THREAD

**Issue by mhuguesaws** [aws/aws-ofi-nccl#719]
The tarball's filename for v1.13.0-aws release does not contain `-aws` to follow the release tag like previous release.
It breaks automation and container files build that uses the tarball following the release tag name.
Was this expected?

v1.13.0-aws tarball filename
`https://github.com/aws/aws-ofi-nccl/releases/download/v1.13.0-aws/aws-ofi-nccl-1.13.0.tar.gz`

v1.12.1-aws tarball filename
`https://github.com/aws/aws-ofi-nccl/releases/download/v1.12.1-aws/aws-ofi-nccl-1.12.1-aws.tar.gz`

**Comment by rauteric** [comment]
Thank you for reporting. We created a new release (with no other changes) to address this: https://github.com/aws/aws-ofi-nccl/releases/tag/v1.13.1-aws.
