### ISSUE TITLE
Clarification needed for NCCL setting recommendation

### ISSUE THREAD

**Issue by kwen2501** [aws/aws-ofi-nccl#76]
Hi Team,

Step 8 of this [EFA guidance](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start-nccl-base.html) seems to recommend the following NCCL settings:

- `NCCL_ALGO=ring` — enables ring algorithm for collective operations.

- `NCCL_PROTO=simple` — instructs NCCL to use a simple protocol for communication. **Currently, the EFA provider does not support LL protocols. Enabling them could lead to data corruption.**

Are they still the recommended settings today? In this recent issue, the recommendation seems to have changed to **NOT** changing any NCCL defaults: https://github.com/aws/aws-ofi-nccl/issues/65#issuecomment-954254543

Any clarification would be much appreciated!

Specifically, does EFA support LL or LL128 today? Or do users still need to set protocol to Simple to avoid data corruptions?

Thank you!

Cc @rohan-varma @zhaojuanmao @pbelevich

**Comment by rashikakheria** [comment]
Hey Ke,

Thanks for reaching out.

Yes, we recommend using `NCCL_ALGO=ring` for large message all reduce as it yields better performance. `NCCL_PROTO=simple` is a must to ensure data consistency when using EFA as a network provider. EFA doesn't support LL and LL128 variants.

Regarding the comment in [#65 (comment)](https://github.com/aws/aws-ofi-nccl/issues/65#issuecomment-954254543), the recommendation was to *NOT* change the default for `NCCL_MIN_NCHANNELS`. All of our recommendations from our [getting started document](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start-nccl-base.html#nccl-start-base-test) applies.

Hope that clarifies.

**Comment by kwen2501** [comment]
Thanks for the clarification @rashikakheria. It really helps!
