### ISSUE TITLE
Handling GDR-capable providers not requested for memory registration

### ISSUE THREAD

**Issue by dmaryin** [aws/aws-ofi-nccl#80]
Hello aws_ofi_nccl maintainers,

For GDR-capable providers which do not request memory registration (i.e. provide FI_HMEM but not FI_MR_HMEM or FI_MR_LOCAL),  there is an issue in current implementation.

The function register_mr_buffers() keeps mr_handle intact, and as it is set to NULL by caller,  mr_handle will be NULL.
Later during ofi_iflush(), NULL mr_handle are being treat as an error condition, which leads to returning ncclSystemError. But having NULL here is normal if provider did not ask for memory registration.
Later during ofi_closeRecv() mr_handle is being passed to fi_close(), and in this case it is NULL, this lead to segfault.

To fix this the following pull request was created https://github.com/aws/aws-ofi-nccl/pull/81
Please consider merging it.

BRs,
Denis

**Comment by rashikakheria** [comment]
Thank you for contributing! Could you let us know about provider against which this PR has been tested?

**Comment by dmaryin** [comment]
Sure. We tested against PSM3 provider.

**Comment by rashikakheria** [comment]
Merged the changes. Resolving issue.
