### ISSUE TITLE
Missed ability to not use memory registering if provider does not request it

### ISSUE THREAD

**Issue by dmaryin** [aws/aws-ofi-nccl#98]
Hello aws-ofi-nccl maintainers,

During our testing with PSM3 provider we faced with abnormal program termination in ofi_iflush phase.
Assumption that provider requires memory registering was reintroduced by recent changes.
Could you please consider merging https://github.com/aws/aws-ofi-nccl/pull/97 which fixes this?

Wanted to discuss the following topic: How to get PSM3 added to the continuous integration plan for aws-ofi-nccl plugin so mistakes like this are detected sooner?

**Comment by rashikakheria** [comment]
Thanks Dmitry for the patch again and we apologize for overriding the previous changes. I have reviewed the patch and have one critical feedback.

The major blocker I see in testing psm3 provider is availability/access to appropriate hardware. Does your team have any continuous integration system that our PRs can use? This will help us prevent such issues in future.

**Comment by dmaryin** [comment]
Hello Rashika (@rashikakheria),

May I ask whether your test\CI system have RoCE or IB (InfiniBand) network card?
If so, PSM3 can be tested there out of the box, it does not require Intel NICs.
PSM3 is fully opensource and shipped with libfabric.

Accessing to our team's test system is a tough topic, I would like to discuss easier approaches first.

BRs,
Denis

**Comment by rashikakheria** [comment]
> May I ask whether your test\CI system have RoCE or IB (InfiniBand) network card?

No, we don't have access to systems with IB or RoCE network card.

**Comment by rashikakheria** [comment]
PR merged.

**Comment by dmaryin** [comment]
> > May I ask whether your test\CI system have RoCE or IB (InfiniBand) network card?
> 
> No, we don't have access to systems with IB or RoCE network card.

Hello Rashika (@rashikakheria),
Sorry for late reply. Unfortunately accessing to our team internal CI infrastructure from outside is a topic required thorough discussion (primarily with infosec representatives). We initiated discussion, but currently the answer is that we are not allowed to do this. I will update if something changes, but chances are low.

**Comment by rashikakheria** [comment]
> Hello Rashika (@rashikakheria), Sorry for late reply. Unfortunately accessing to our team internal CI infrastructure from outside is a topic required thorough discussion (primarily with infosec representatives). We initiated discussion, but currently the answer is that we are not allowed to do this. I will update if something changes, but chances are low.

Thanks for getting back! One idea is that you could possibly pull in the changes from `aws-ofi-nccl` repository for every PR and test it on your end. You could comment on the PRs if your CI system break (until the time this repository has direct access to your testing).
